### ISSUE TITLE
Get AstroDrizzle to run away from STScI

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#10]
Because I am trying to run astrodrizzle at SIUE and not as STScI astrodrizzle is having problems. 

Initially these problems seemed to be caused by the fact that my laptop couldn't access the central store area in the `$uref` environment variable.  To address this I downloaded all the "Best Reference Files" for a test image, `u2j70101t_c0m.fits` from proposal 05489. This included having to download the `IDCTAB` file separately from the other reference files using the uref ftp page.

Now, astrodrizzle runs-ish. It gives unhelpful messages in the log file.  

Additionally, the MAST ftp site has not been cooperating.

**Comment by acviana** [comment]
The closest thing it gives to a useful error message is this:

```
Traceback (most recent call last):
  File "/usr/stsci/pyssgx/2.7.stsci_python/drizzlepac/util.py", line 208, in wrapper
    func(*args, **kwargs)
  File "/usr/stsci/pyssgx/2.7.stsci_python/drizzlepac/astrodrizzle.py", line 213, in run
    procSteps=procSteps)
  File "/usr/stsci/pyssgx/2.7.stsci_python/drizzlepac/createMedian.py", line 95, in createMedian
    _median(imgObjList, paramDict)
  File "/usr/stsci/pyssgx/2.7.stsci_python/drizzlepac/createMedian.py", line 322, in _median
    fillval=fillval                      # turn on use of imedian/imean
  File "/usr/stsci/pyssgx/2.7.stsci_python/drizzlepac/minmed.py", line 98, in __init__
    nkeep=1,upper=None,lower=None)
  File "/usr/stsci/pyssgx/2.7.stsci_python/stsci/image/numcombine.py", line 82, in __init__
    raise ValueError, "Rejecting more pixels than specified by the nkeep parameter!"
ValueError: Rejecting more pixels than specified by the nkeep parameter!
```

However, the nkeep parameter is not a parameter in the config files so I can't adjust it. I still think this is something wrong with the reference files but it's not complaining about anything missing. The only other error in the log is earlier when it says:

```
[ERROR   ] ##############################################################################
[ERROR   ] #                                                                            #
[ERROR   ] # ERROR:                                                                     #
[ERROR   ] # AstroDrizzle Version 4.3.2 encountered a problem!  Processing terminated   #
[ERROR   ] # at 12:24:45.55 (20/08/2012).                                               #
[ERROR   ] #                                                                            #
[ERROR   ] ##############################################################################
```

**Comment by acviana** [comment]
So here's another clue:

```
In [5]: drizzlepac.astrodrizzle.__version__
Out[5]: '4.3.2'
```

Astrodrizzle is on version 1 something. Megan Sosey thinks my paths are messed up. I tried running 

```
> unsetenv PYTHONPATH
> irafx
```

to reset things but I got the same result. Maybe I need to reinstall irafx?

**Comment by acviana** [comment]
I think I'm going to punt on this in favor of working on getting some png's to Pamela's team.
