### ISSUE TITLE
Unable to create ephem_viewer image.

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#41]
```
> python ephem/ephem_viewer.py -file /Users/viana/mtpipeline/archive/09393_neptune/png/u8fa0202m_cr_c0m_wide_single_sci_linear.png
Traceback (most recent call last):
  File "ephem/ephem_viewer.py", line 123, in <module>
    ephem_viewer_main(args.file)
  File "ephem/ephem_viewer.py", line 98, in ephem_viewer_main
    ep.getEphem()
  File "ephem/ephem_viewer.py", line 61, in getEphem
    'No record found in master_finders_query'
AssertionError: No record found in master_finders_query
```

**Comment by acviana** [comment]
Ran this:

```
> python build_master_table.py -filelist '/Users/viana/mtpipeline/archive/*neptune/png/*_single_sci_linear.png'
```

Got the same result.

**Comment by acviana** [comment]
Ran this:

```
> python run_ephem.py -filelist '/Users/viana/mtpipeline/archive/*neptune/*_single_sci.fits'
```

Got the same result.

**Comment by acviana** [comment]
There is a record in the `master_images` table.

```
SELECT count(*) 
FROM mtpipeline.master_images
WHERE name = 'u8fa0202m_cr_c0m_wide_single_sci_linear.png';
```

Returns 1

**Comment by acviana** [comment]
But performing a `JOIN` into the `master_finders` table doesn't turn up anything. So the ephemerides were never downloaded.

```
SELECT count(*) 
FROM mtpipeline.master_images
JOIN mtpipeline.master_finders
ON master_images.id = master_finders.master_images_id
WHERE name = 'u8fa0202m_cr_c0m_wide_single_sci_linear.png';
```

Returns 0.

**Comment by acviana** [comment]
Digging a little more we can see what not all the directories have ephemerides

```
SELECT DISTINCT(file_location)
FROM mtpipeline.master_images
JOIN mtpipeline.master_finders
ON master_images.id = master_finders.master_images_id
WHERE master_finders.object_name = 'neptune';
```

This returns the first 5 directories.
