### ISSUE TITLE
c1m.fits files 'missing'

### ISSUE THREAD

**Issue by walyssonBarbosa** [STScI-Citizen-Science/MTPipeline#95]
Figure out why the pipeline is crashing in some `c1m.fits` files.

They are in their folder but `fits` cannot read them:

``` python
from astropy.io import fits
 hdulist = fits.open('/astro/mtpipeline/mtpipeline_outputs/wfpc2/11971_kbo_haumea/uba0011vm_cr_c1m.fits')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 116, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, **kwargs)
  File "/sw/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 248, in fromfile
    save_backup=save_backup, **kwargs)
  File "/sw/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 759, in _readfrom
    ffo = _File(fileobj, mode=mode, memmap=memmap)
  File "/sw/lib/python2.7/site-packages/astropy/io/fits/file.py", line 125, in __init__
    raise IOError('File does not exist: %r' % fileobj)
```

```
$ ls /astro/mtpipeline/mtpipeline_outputs/wfpc2/11971_kbo_haumea/uba0011vm_cr_c1m.fits
/astro/mtpipeline/mtpipeline_outputs/wfpc2/11971_kbo_haumea/uba0011vm_cr_c1m.fits
```

**Comment by acviana** [comment]
Can you open the file using astropy.io from the IPython shell?

**Comment by walyssonBarbosa** [comment]
I couldn't open it in the IPython shell.

It seems that they are only symbolic links:

```
$ ls -l /astro/mtpipeline/mtpipeline_outputs/wfpc2/11971_kbo_haumea/uba0011wm_cr_c1m.fits
lrwxrwxrwx  1 wbarbosa  STSCI\science  78 Jun 24 01:20 /astro/mtpipeline/mtpipeline_outputs/wfpc2/11971_kbo_haumea/uba0011wm_cr_c1m.fits -> /astro/mtpipeline/mtpipeline_outputs/wfpc2/11971_kbo_haumea/uba0011wm_c1m.fits
```

**Comment by walyssonBarbosa** [comment]
I removed all symlinks and put the pipeline to run in the folder again, hopefully it will complete now.

Changed `run_imaging_pipeline.py` just to get `c0m.fits` files.

**Comment by acviana** [comment]
Did it work? All the the `cr_c1m.fits` files are just symbolic links to the `_c1m.fits` files because they are exactly the same.

**Comment by walyssonBarbosa** [comment]
Yes, it did. Almost all missing files were created. Just a few png files to go.

**Comment by acviana** [comment]
Great!
